const
	id_MConfig      =   209;{menu item to open configure dialog}
        ID_MOpen        =   202;{menu }
	ID_MCLose       =   201;{menu }
	id_MAbout       =   203;{menu }
	id_MExit        =   206;{menu }
	Id_MMinimize    =   204;{menu }
	Id_MShow        =   205;{menu }
	Id_MAutoY       =   207;{menu }
	Id_MAutoN       =   208;{menu }
        ID_Advanced     =   210;
	ID_CDOpen       =   101;{Dialog}
	ID_CDClose      =   102;{Dialog}
	ID_Close        =   103; {Dialog}
        ID_SystemMenu   =   301;
        ID_SYSICON      =   1;
        ID_Hotkey1      =   100;
        ID_Hotkey2      =   101;
        ID_Hotkey3      =   102;
                   
