const          

   CONFIQ              =	1;{сам диалог}
   ID_EXITAPP_EDIT     =	201;{эдит-текст в нём- хоткей для закрытия CDTOOL}
   ID_CLOSE_EDIT       =	202;{--"----"----"----"----"----"----"---- CdRom}
   ID_OPEN_EDIT        =	203;{--"----"----"----"----"----"открытия CDRom  }
   ID_LABEL3           =	401;{текст}
   ID_APPLY_BUTTON     =	101;
   ID_HOW_TO           =	102;
   ID_CANCEL_BUTTON    =        103;
   IDC_GROUPBOX1       =        301;
   IDC_STATICFRAME1    =        302;
   ID_USER_RADIO       =        501;
   IDC_STATICTEXT1     =	104;
   ID_MACHINE_RADIO    =        502;	
   
